controller_manager:
  ros__parameters:
    update_rate: 100  # Update rate of the controller in Hz
    
    # Configuration for simple_diff_drive_controller
    simple_diff_drive_controller:
      type  : diff_drive_controller/DiffDriveController

    # Configuration for joint_state_broadcaster
    joint_state_broadcaster:
      type  : joint_state_broadcaster/JointStateBroadcaster

# Configuration for simple_diff_drive_controller
simple_diff_drive_controller:
  ros__parameters:
    left_wheel_names  : ['rear_wheel_left_joint'] # List of names of the left wheels
    right_wheel_names : ['rear_wheel_right_joint'] # List of names of the right wheels
    publish_rate: 50.0  # default: 50 # Rate at which the controller publishes twist commands            
    # Covariance diagonal for pose measurements
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # Covariance diagonal for twist measurements
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.26
    wheel_radius : 0.1

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.25
    use_stamped_vel: false
    
    # Base frame_id
    base_frame_id: base_link #default: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true # Whether linear x velocity has limits
        max_velocity           : 1.0  # Maximum linear x velocity in m/s
        min_velocity           : -0.5 # Minimum linear x velocity in m/s
        has_acceleration_limits: true # Whether linear x acceleration has limits
        max_acceleration       : 0.8  # Maximum linear x acceleration in m/s^2
        min_acceleration       : -0.4 # Minimum linear x acceleration in m/s^2
        has_jerk_limits        : true # Whether linear x jerk has limits
        max_jerk               : 5.0  # Maximum linear x jerk in m/s^3
    angular:
      z:
        has_velocity_limits    : true # Whether angular z velocity has limits
        max_velocity           : 1.0  # Maximum angular z velocity in rad/s
        has_acceleration_limits: true # Whether angular z acceleration has limits
        max_acceleration       : 1.5  # Maximum angular z acceleration in rad/s^2 
        has_jerk_limits        : true # Whether angular z jerk has limits
        max_jerk               : 2.5  # Maximum angular z jerk in rad/s^3 

